version: '3.3'

services:
  database:
    image: postgres:13.0-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Alpha140
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  redis:
    image: redis:5-alpine
    ports: [ 6379 ]

volumes:
  db-data:

